### PR TITLE
Allow json benchmark output 

### PR DESCRIPTION
**Pull request by gs0510**
& add bench target to Makefile

### CODE REVIEW

**Review by dinosaure — CHANGES_REQUESTED** [review]
I'm sorry but `conduit` is deep in the stack and we should not introduce a new dependency on it 😕 . Can you produce a `json` output without PPX and Yojson?

**Comment by avsm** [comment]
This is only for benchmarking though: can't it be a depopt?

**Comment by dinosaure** [comment]
Hmmhmm I'm not sure in which context the benchmark is running (it can run as a _test_ and, in this case we can tag this dependency with `{with-test}`). Otherwise, a `depopts` with `(optional)` is fine - but, in that case  we should extend the CI to ensure that the benchmark still builds.

**Comment by hannesm** [comment]
I don't know much about your benchmarking setup, but please note that we have https://github.com/mirage/metrics specifically for such a use case "separate the reporting from the collection". With metrics, the "core" library is very slim (and should not be an issue to integrate into your library - exposing one or many metrics sources), while the reporter can be installed by the application - which can be a simple text outputter, or a json or sexp or whatever outputter. IMHO the metrics library (similarly to logs) separates the collection from the reporting, and makes a lot of sense in respect to dependency cone.

**Comment by samoht** [comment]
What we've done in [other packages](https://github.com/mirage/irmin/blob/master/irmin-bench.opam) is to have an explicit `*-benchmark` opam package to hold these kinds of dependencies. Maybe that would help to do the same thing here?

**Comment by gs0510** [comment]
> Hmmhmm I'm not sure in which context the benchmark is running (it can run as a _test_ and, in this case we can tag this dependency with `{with-test}`). Otherwise, a `depopts` with `(optional)` is fine - but, in that case we should extend the CI to ensure that the benchmark still builds.

I would be running the `bench` target from the Makefile, but would only want to run the benchmarks and not other tests. Is there a solution out of the ones listed here that is more preferred than the others?

**Comment by samoht** [comment]
I think we should avoid using depopts dependencies as much as possible -- it brings non-determinism and a lot of recompilation to our users.

I think we shoud go with creating an additional `conduit-bench` target ; Looping in @CraigFe who has already had to solve these issues for irmin and index: we should solve that issue in a consistent way to ease the job of the continuous benchmark infrastructure that @gs0510 is working on.

**Comment by gs0510** [comment]
@samoht I talked to @dinosaure offline, and he recommends creating a `conduit-bench.opam`, so I'll go ahead with that since it would also make things more uniform.

**Review by dinosaure — APPROVED** [review]

**Comment by dinosaure** [comment]
Thanks!

**Pull request merged**
