### PR TITLE
the API of Tls_mirage.client_of_flow was changed in master

### PR DESCRIPTION
**Pull request by hannesm**
see https://github.com/mirleft/ocaml-tls/pull/336

### CODE REVIEW

**Comment by hannesm** [comment]
(depending on your conduit release plans, this should be hold off till a new tls release is done (likely once MirageOS3 is released))

**Comment by avsm** [comment]
We can cut a release just for this before any other changes I think

**Comment by hannesm** [comment]
I don't have any plans to cut a TLS release too soon (rather wait till happy with the API).

**Comment by avsm** [comment]
Well, we'll have to cut one with the rest of the Mirage3 when the first dev is cut, right?  That's when the conduit release can come out too.

**Comment by hannesm** [comment]
sure.  what I tried to express is that since conduit is used for other things (than MirageOS), there might be a reason to publish a conduit release before Mirage3.  But I don't follow conduit development.

**Comment by hannesm** [comment]
now have a mirage-dev branch, and this in it

**Pull request closed without merging**
