### PR TITLE
fix mirage tests

### PR DESCRIPTION
**Pull request by vbmithr**
Tried to compile mirage tests. Apparently nobody tested that for a little while. I fixed warnings, and so on, but it fails at `make`: seems the `main.ml` is generated invalid and does not compile against latest Mirage. Can anybody help?

### CODE REVIEW

**Comment by yomimono** [comment]
There's a branch for compiling against the 3.0.0 mirage libraries at https://github.com/mirage/ocaml-conduit/tree/mirage-dev .  Are you getting failures with mirage 2.9.1 and the current master of conduit?

**Comment by vbmithr** [comment]
On 02/12/2016 15:31, Mindy Preston wrote:
> Are you getting failures with mirage 2.9.1 and the current master of
> conduit?

Yes, exactly.

**Comment by yomimono** [comment]
Thanks @vbmithr, I'll take a look.

**Comment by yomimono** [comment]
I couldn't push to your branch, so I've opened #169 with more changes on top of your fixes.  Thanks for pointing this out, @vbmithr - these have been broken since `mirage` version 2.7.0, I think.

**Pull request merged**
