### PR TITLE
Use pa_sexp_conv and bump to 0.11

### PR DESCRIPTION
**Pull request by avsm**
This lets us leap the Core >=113.24 constraint without a full switch to ppx (which requires some dependent changes in #122

### CODE REVIEW

**Comment by dsheets** [comment]
`opam` file says 4.02.0 but `CHANGES` says 4.02.3. Is 4.02.3 really necessary? Is it a ppx thing?

**Comment by rgrinberg** [comment]
Failure on alpine linux:

```
# src/bigstring_stubs.c:36:24: fatal error: sys/endian.h: No such file or directory
```

**Comment by rgrinberg** [comment]
@dsheets Hopefully the next release will not longer use type_conv and ppx_deriving/ppx_type_conv require >= 4.02.3

**Comment by rgrinberg** [comment]
Anyway the alpine issue is a core issue so I'm merging this.

**Pull request merged**
