### PR TITLE
Fix discover.ml

### PR DESCRIPTION
**Pull request by edwintorok**
/cc @rgrinberg

### CODE REVIEW

**Comment by rgrinberg** [comment]
Haha, that is very embarrassing.

**Comment by edwintorok** [comment]
I'm thinking about adding a few more tests to the matrix (in a separate PR), obviously we can't test all 2^depopts combinations, but having these 2 combinations should cover the main ones: DEPOPTS=`lwt ssl` DEPOPTS=`lwt tls`. What do you think?

**Comment by rgrinberg** [comment]
I agree on expanding it but your 2 main ones exclude mirage and async so it's not really that extensive.

@avsm what do you think?

**Comment by edwintorok** [comment]
Should we also have: `DEPOPTS="async"` and `DEPOPTS="lwt mirage-dns"`? (in addition to the current one, which I'd of course keep: `DEPOPTS="async_ssl lwt mirage-dns ssl tls"`)

**Comment by rgrinberg** [comment]
I think that would be pretty complete then @edwintorok

**Pull request merged**
