### PR TITLE
Revamp config step

### PR DESCRIPTION
**Pull request by rgrinberg**
Rewrite it in pure OCaml. Now you just need to run:

```
$ ocaml discover.ml
```

And subsequence `$ make` calls will be incremental.

### CODE REVIEW

**Comment by rgrinberg** [comment]
OK this ready. Can also get rid of sed if people ask for it.

cc @avsm @vbmithr

**Comment by avsm** [comment]
thanks! /cc @djs55 to clear Windows build as well.

**Comment by samoht** [comment]
btw, the sed thing could be replaced by `topkg` watermarking if needed:

https://github.com/samoht/irmin-watcher/blob/master/pkg/pkg.ml#L23-L24
https://github.com/samoht/irmin-watcher/blob/master/pkg/META.in#L3

**Comment by rgrinberg** [comment]
Good point. I'll take a look at topkg'ing conduit as well. we're not using oasis
for the install scripts, so there's probably quite a few benefits to be reaped
here.

**Comment by rgrinberg** [comment]
@dsheets friendly ping

**Comment by dsheets** [comment]
What do I need to do? Maybe you meant @djs55, @rgrinberg?

**Comment by rgrinberg** [comment]
Was a little too eager on the tab complete. Yes I meant @djs55 .

**Comment by avsm** [comment]
Sorry about the delay, this is on my list to look at on my new Windows laptop!

**Comment by vbmithr** [comment]
@rgrinberg Works for me! Good to merge IMO.

**Comment by rgrinberg** [comment]
@vbmithr, awesome did you test on windows?

Eager to merge this once we know it works everywhere. The cross platform
requirements for the mirage folks seem to be higher these days :)

**Comment by vbmithr** [comment]
On 19/09/2016 02:55, Rudi Grinberg wrote:
> @vbmithr, awesome did you test on windows?

No I did not. I tested on Linux as usual.

**Comment by rgrinberg** [comment]
@avsm ping

**Comment by avsm** [comment]
on it, bikeshedded a bit on the topkging but almost there...

**Pull request merged**
