### PR TITLE
Prepare 0.14.4

### PR DESCRIPTION
**Pull request by rgrinberg**
two releases in 1 day.

Very agile!

### CODE REVIEW

**Comment by samoht** [comment]
Does it fix the test breakage as well? If not, maybe we should just disable the tests in the release versions?

**Comment by rgrinberg** [comment]
It fixes building the tests. I think some people may still have issues running them #187 but those seem to be more rare.

**Comment by edwintorok** [comment]
I wouldn't mind if tests are disabled in opam until we can actually run them from Travis.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/8197

**Comment by rgrinberg** [comment]
OK, thanks for fixing opam-repository.

@edwintorok what's preventing us from running the tests in travis?

**Comment by edwintorok** [comment]
I haven't had time to work on this yet: https://github.com/ocaml/ocaml-ci-scripts/pull/145. Basically we need a way to tell opam to run the tests for just 1 package, not for every of it dependencies too. One way to do that is to install all dependencies without `-t`, and then do a `-t` on the package. However this would also need to parse a dry-run/json output of opam to figure out what those packages are (using `jq` (or something else with minimal dependencies)). I tried a simpler solution that just did `opam install --deps-only package` install followed by a `opam install -t package`, but that still installs and runs the tests of some test-only dependencies. This in turn breaks the CI of other projects (because their test-only deps' tests may not work).

**Comment by talex5** [comment]
https://github.com/ocaml/opam/issues/2277#issuecomment-250056045 and https://github.com/ocaml/opam/issues/2190 seem to suggest that the `-t` problem is fixed in opam 2.

**Comment by rgrinberg** [comment]
OK I've disabled the tests as recommended.

**Pull request merged**
