### PR TITLE
No vchan port sexp, and mirage-flow 4 support

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by avsm** [comment]
Missing pin?

```
File "src/conduit-mirage/conduit_mirage.ml", line 239, characters 17-29:
239 |       | TLS f -> TLS.shutdown f mode
                       ^^^^^^^^^^^^
Error: Unbound value TLS.shutdown
```

**Comment by hannesm** [comment]
Yes and no. So, tls since 0.17.4 has a shutdown function. The CI here fails since vchan only since 6.0.2 (PRed to opam-repository) supports mirage-flow 4.

So, once https://github.com/ocaml/opam-repository/pull/25765 is merged, we'll hopefully get this CI check to be green and can merge and release a conduit with shutdown functionality :)

**Comment by hannesm** [comment]
CI looks fine, there's a failure in conduit_async.ml with OCaml 5.2:

```OCaml
module V1 = V1
module V2 = V2
module V3 = V3

[@@@deprecated "Use Conduit_async.V1"]

include V1.Conduit_async
```

and the error is "Error (warning 53 [misplaced-attribute]): the "deprecated" attribute cannot appear in this context" -- any hints where to put it - how to change the implementation?

**Comment by hannesm** [comment]
FreeBSD failures are tracked in https://github.com/janestreet/core_unix/issues/11

**Pull request merged**
