### PR TITLE
Avoid shutdown race condition on service startup

### PR DESCRIPTION
**Pull request by CraigFe**
Fix https://github.com/mirage/ocaml-conduit/issues/352. The `lwt` and `async` service loops previously took condition variables that were used to signal when to shutdown. This resulted in a race condition: the shutdown signal can be broadcast before the server is waiting on it.

Fixed by having the service loops take switches as configuration instead:

```ocaml
val Conduit_lwt.serve   : ?stop:Lwt_switch.t    -> ... -> cfg -> unit Lwt.t
val Conduit_async.serve : ?stop:unit Deferred.t -> ... -> cfg -> unit Deferred.t
```
The most closely corresponding definitions would probably have `Conduit_async.serve` taking an `Ivar.t` instead, but from a glance at similar service loops in the ecosystem it seems to be more common to use a `Deferred.t` instead. Happy to change that if you think it's more appropriate.

### CODE REVIEW

**Review by dinosaure — APPROVED** [review]
May be, in your case in Irmin, it can be interesting to add a new argument `launched` which signals that the server was properly launched after that? Note that it could useful for us, in our tests, when we need to `sleep` a bit with `async` before to connect clients.

**Comment by CraigFe** [comment]
I spent a while thinking about ways to know that the server is ready to receive messages, and I'm not sure it can be done with `Lwt`. As you say, we would want to emit a signal after the first time that `accept` blocks, but  without knowing how `accept` is implemented we can't pull any tricks with the scheduler to get a signal out after that thread sleeps (e.g. it might contain several non-blocking portions, and we don't know how many).

I'd be very happy to be proven wrong on this though; currently this seems like a pretty annoying limitation of Lwt and of concurrency monads more generally.

**Comment by dinosaure** [comment]
> I spent a while thinking about ways to know that the server is ready to receive messages, and I'm not sure it can be done with Lwt. As you say, we would want to emit a signal after the first time that accept blocks, but without knowing how accept is implemented we can't pull any tricks with the scheduler to get a signal out after that thread sleeps (e.g. it might contain several non-blocking portions, and we don't know how many).

`Service.init` should be enough. The main error is when a client wants to connect to a specific port which is not yet bound. In a certain sense, `Service.init` _allocates_ the ressource and initialise it - so, about `Conduit_lwt.TCP` for example, it allocates the _socket_ and `bind_ it. At this stage, you can launch a client cooperatively.

**Comment by CraigFe** [comment]
Good point. I've done as you suggest in https://github.com/mirage/ocaml-conduit/pull/371.

**Comment by samoht** [comment]
I've just switched the `master` branch and the `v3` branch. If you are still interested by experimenting on the v3 API, would you mind re-opening a PR vs the v3 branch?

**Pull request closed without merging**
